### ISSUE TITLE
empty result on simple sentence

### ISSUE THREAD

**Issue by randomgambit** [peter3125/enhanced-subject-verb-object-extraction#11]
Hi @peter3125 , this is really great!! Thanks for writing this code.

Consider this simple sentence:

`expert spacy users, as measured by the recent polls, have been very kind`

Your code returns an empty list, unable to find the subject + verb + object of the sentence. Do you know why?

Thanks!

**Comment by rock3125** [comment]
Hi!  that is a really good question.  I think the part in the middle "as measured by recent polls" might throw it off finding the verb.  I'm not sure if it copes with fractured sentences like this one.  Have you tried just "expert spacy users have been very kind"?

**Comment by randomgambit** [comment]
thanks! It does not work either

```
findSVOs(nlp("Seated in Mission Control, Chris Kraft neared the end of a tedious Friday afternoon as he monitored a " \
       "seemingly interminable ground test of the Apollo 1 spacecraft."))
Out[68]: 
[('Chris Kraft', 'neared', 'the end of a tedious Friday afternoon'),
 ('he', 'monitored', 'a interminable ground test of the Apollo spacecraft')]

findSVOs(nlp("expert spacy users have been very kind"))
Out[69]: []

```
I wonder if, much more simply, the code does not allow a sentence with just subject + verb (no object) as above. What do you think?

Thanks!

**Comment by rock3125** [comment]
strange - I've just put through a whole raft of items - and none of them is working. 

"expert spacy users are very kind"
expert compound ADJ spacy [] []
spacy compound ADJ users ['expert'] []
users nsubj NOUN are ['spacy'] []
are ROOT AUX are ['users'] ['kind']
very advmod ADV kind [] []
kind acomp ADJ are ['very'] []
[]

"expert spacy users are very kind to me"
expert compound ADJ spacy [] []
spacy compound ADJ users ['expert'] []
users nsubj NOUN are ['spacy'] []
are ROOT AUX are ['users'] ['kind']
very advmod ADV kind [] []
kind acomp ADJ are ['very'] ['to']
to prep ADP kind [] ['me']
me pobj PRON to [] []
[]

"expert spacy users are very kind to dogs"
expert compound ADJ spacy [] []
spacy compound ADJ users ['expert'] []
users nsubj NOUN are ['spacy'] []
are ROOT AUX are ['users'] ['kind']
very advmod ADV kind [] []
kind acomp ADJ are ['very'] ['to']
to prep ADP kind [] ['dogs']
dogs pobj NOUN to [] []
[]

"spacy users are very kind to dogs"
spacy compound ADJ users [] []
users nsubj NOUN are ['spacy'] []
are ROOT AUX are ['users'] ['kind']
very advmod ADV kind [] []
kind acomp ADJ are ['very'] ['to']
to prep ADP kind [] ['dogs']
dogs pobj NOUN to [] []
[]

"spacy users are kind to dogs"
spacy compound ADJ users [] []
users nsubj NOUN are ['spacy'] []
are ROOT AUX are ['users'] ['kind']
kind acomp ADJ are [] ['to']
to prep ADP kind [] ['dogs']
dogs pobj NOUN to [] []
[]

"users are kind to dogs"
users nsubj NOUN are [] []
are ROOT AUX are ['users'] ['kind']
kind acomp ADJ are [] ['to']
to prep ADP kind [] ['dogs']
dogs pobj NOUN to [] []
[]

"users are dogs"
users nsubj NOUN are [] []
are ROOT AUX are ['users'] ['dogs']
dogs attr NOUN are [] []
[]

the last one at least should work?  looking into it now...

**Comment by rock3125** [comment]
that is very strange - spacy seems to be confused with the verb function.  In "users are dogs" spacy reckons that "are" is an auxiliary verb - but "are" isn't used in an auxiliary position!  It is the main verb, not auxiliary to the main verb (eg. in "have been", "have" is auxiliary to "been" - the verb here is "to be" in passive form)...   let me see if I can modify the _is_non_aux_verb() function a little... dangerous though it is!

**Comment by randomgambit** [comment]
thanks! Looking forward to it

**Comment by rock3125** [comment]
@randomgambit I've made a new branch called "minor-improvements" - it returns SVOs where the O is missing, has a small test_example.py showing this and it "fixes" the missing main "Verb" when its marked as "AUX".  This is just a small fix.  Honestly, I think the programmatic approach to finding SVOs in English is doomed.  I think a neural network might have better luck at this than 1000s of handwritten rules.  Good luck  :)

**Comment by randomgambit** [comment]
Thanks @peter3125 this is great. I will let you know if I find other interesting cases. I like the fact that we can at least understand what is going on when we play with the POS tags. The issue with neural network is that it works.... but you dont know why. And if it does not work, you cannot fix it easily...

**Comment by randomgambit** [comment]
@peter3125 I think the branch is not visible? I dont see it on github?

**Comment by rock3125** [comment]
so sorry - not sure what happened - I got desperate and merged it into the main branch - just stick to master and get it  :)

**Comment by randomgambit** [comment]
it works! The only remaining issue is that the code discards some parts of the verb, say

```
findSVOs(nlp('the pressure has become much tighter'))
Out[20]: [('the pressure', 'become')]
```

how can I make sure the function also returns tighter in this case? This seems like a pretty common case.

Thanks!!!

**Comment by rock3125** [comment]
not sure why 'tighter' isn't being picked up.  It is an adjective in an "acomp" relationship.  Take a look at displacy, a handy tool for analyzing such relationships.

https://explosion.ai/demos/displacy?text=the%20pressure%20has%20become%20much%20tighter&model=en_core_web_sm&cpu=1&cph=1

The verb-phrase could possibly be extended by including the left and right chunks of the verb (ie. parts of a Verb Phrase) by looking at these words relative to the verb.
