### ISSUE TITLE
extracting subject verb object regardless of word order

### ISSUE THREAD

**Issue by edgar2597** [peter3125/enhanced-subject-verb-object-extraction#7]
Hi. I wonder is it possible to extract subject verb object using this extractor regardless of word order?  If it's possible, could you please tell me how?

**Comment by rock3125** [comment]
Hi Edgar, sounds like you're talking about passive / active sentences?
("John caught the ball" vs. "the ball was caught by John").  Now..  this world of ours is moving fast.  This SVO stuff here is quite primitive compared to the state of the art.  Alas - I couldn't find the repository I saw that did exact SVO using BERT.  BUT!  Please - start looking at BERT and RoBERTa.  Here's a link that might be of some use;

https://github.com/pytorch/fairseq/blob/master/examples/roberta/README.md

As I said - I couldn't find back that SVO thing I saw - but this is the future of NLP, not this much simpler "algorithmic" approach to language.

To be honest Edgar, I think that SVO itself isn't that useful per se.  Language is much more complex than simple SVO.  SVO is probably a good place to start, but there are complex and intricate relationships between all parts of a sentence.  Take a look at Spacy - my personal favorite parser;

https://explosion.ai/demos/displacy

it shows relationships like dobj (dependent objects), nsubj (noun subjects), verbs etc.  A much better approach imho - and really easy to do.  One friendly word of warning - natural language is always very complex!

**Comment by edgar2597** [comment]
> Hi Edgar, sounds like you're talking about passive / active sentences?
> ("John caught the ball" vs. "the ball was caught by John"). Now.. this world of ours is moving fast. This SVO stuff here is quite primitive compared to the state of the art. Alas - I couldn't find the repository I saw that did exact SVO using BERT. BUT! Please - start looking at BERT and RoBERTa. Here's a link that might be of some use;
> 
> https://github.com/pytorch/fairseq/blob/master/examples/roberta/README.md
> 
> As I said - I couldn't find back that SVO thing I saw - but this is the future of NLP, not this much simpler "algorithmic" approach to language.
> 
> To be honest Edgar, I think that SVO itself isn't that useful per se. Language is much more complex than simple SVO. SVO is probably a good place to start, but there are complex and intricate relationships between all parts of a sentence. Take a look at Spacy - my personal favorite parser;
> 
> https://explosion.ai/demos/displacy
> 
> it shows relationships like dobj (dependent objects), nsubj (noun subjects), verbs etc. A much better approach imho - and really easy to do. One friendly word of warning - natural language is always very complex!

Thanks a lot for the link. Yeah i was looking for some instrument to do kind of linguistic inversion (like your example ("John caught the ball"  "the ball was caught by John")). A reason why I wanted to use SVO extractor is cause I am working with Russian language and there's no constituency parser for it so I thought at least I can extract subject object and verb and swap them in all possible ways.
